import React, { useState } from 'react';
import { Download, FileSpreadsheet, IndianRupee, ArrowDownRight, ArrowUpRight, Printer } from 'lucide-react';
import { Expense, Invoice } from '../../types';

interface MonthlyPnLProps {
  invoices: Invoice[];
  expenses: Expense[];
}

export const MonthlyPnL: React.FC<MonthlyPnLProps> = ({ invoices, expenses }) => {
  const [selectedMonth, setSelectedMonth] = useState('2026-08'); // YYYY-MM

  // Available months derived from data
  const allMonths = Array.from(
    new Set([
      ...invoices.map((i) => i.issuedAt.slice(0, 7)),
      ...expenses.map((e) => e.date.slice(0, 7)),
      '2026-08',
      '2026-09',
    ])
  ).sort().reverse();

  // Filter invoices for selected month
  const monthInvoices = invoices.filter((i) => i.issuedAt.startsWith(selectedMonth));
  const totalIncome = monthInvoices.reduce((sum, i) => sum + i.amount, 0);

  // Filter expenses for selected month
  const monthExpenses = expenses.filter((e) => e.date.startsWith(selectedMonth));
  const totalExpense = monthExpenses.reduce((sum, e) => sum + e.amount, 0);

  const netSurplus = totalIncome - totalExpense;

  const monthLabel = new Date(`${selectedMonth}-01`).toLocaleDateString('en-IN', {
    month: 'long',
    year: 'numeric',
  });

  const handleDownloadCSV = () => {
    let csv = `Nurturing Minds Therapy Center - Monthly Income & Expense Statement\n`;
    csv += `Month: ${monthLabel}\n`;
    csv += `Generated by: Dr. Sweety Bhatnagar\n\n`;

    csv += `INCOME (PAID INVOICES)\n`;
    csv += `Invoice No,Date,Description,Amount (INR)\n`;
    monthInvoices.forEach((inv) => {
      csv += `"${inv.invoiceNumber}","${inv.issuedAt.slice(0, 10)}","${inv.description.replace(/"/g, '""')}",${inv.amount}\n`;
    });
    csv += `Total Income,,,${totalIncome}\n\n`;

    csv += `EXPENSES (LOGGED EXPENDITURE)\n`;
    csv += `Date,Payee,Category,Amount (INR)\n`;
    monthExpenses.forEach((exp) => {
      csv += `"${exp.date}","${exp.payee.replace(/"/g, '""')}","${exp.category}",${exp.amount}\n`;
    });
    csv += `Total Expenses,,,${totalExpense}\n\n`;

    csv += `NET OPERATING SURPLUS,,,${netSurplus}\n`;

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `NurturingMinds_Income_Expense_${selectedMonth}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Header & Month Selector */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <FileSpreadsheet className="w-5 h-5 text-[#6D0281]" />
            Monthly Income-and-Expense Statement
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Simple cash inflow (invoices) vs. outflow (expenses). Not a corporate balance sheet.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <select
            value={selectedMonth}
            onChange={(e) => setSelectedMonth(e.target.value)}
            className="text-xs border border-slate-200 rounded-xl px-3 py-2 bg-white text-slate-800 font-semibold focus:outline-none focus:ring-2 focus:ring-[#6D0281]"
          >
            {allMonths.map((m) => {
              const label = new Date(`${m}-01`).toLocaleDateString('en-IN', {
                month: 'long',
                year: 'numeric',
              });
              return (
                <option key={m} value={m}>
                  {label}
                </option>
              );
            })}
          </select>

          <button
            onClick={handleDownloadCSV}
            className="px-3.5 py-2 bg-purple-50 hover:bg-purple-100 text-[#6D0281] text-xs font-semibold rounded-xl border border-purple-200 transition flex items-center gap-1.5"
            title="Download CSV report"
          >
            <Download className="w-3.5 h-3.5" />
            CSV Export
          </button>

          <button
            onClick={handlePrint}
            className="p-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl transition"
            title="Print statement"
          >
            <Printer className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* 3 Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        {/* Total Inflow */}
        <div className="bg-white p-5 rounded-2xl border border-purple-100/80 shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">
              Total Inflow (Receipts)
            </span>
            <div className="p-1.5 rounded-lg bg-emerald-50 text-emerald-600">
              <ArrowUpRight className="w-4 h-4" />
            </div>
          </div>
          <p className="text-2xl font-extrabold text-emerald-700 mt-2">
            ₹ {totalIncome.toLocaleString('en-IN')}
          </p>
          <p className="text-[11px] text-slate-400 mt-1">
            {monthInvoices.length} paid invoices in {monthLabel}
          </p>
        </div>

        {/* Total Outflow */}
        <div className="bg-white p-5 rounded-2xl border border-purple-100/80 shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">
              Total Outflow (Expenses)
            </span>
            <div className="p-1.5 rounded-lg bg-rose-50 text-rose-600">
              <ArrowDownRight className="w-4 h-4" />
            </div>
          </div>
          <p className="text-2xl font-extrabold text-rose-700 mt-2">
            ₹ {totalExpense.toLocaleString('en-IN')}
          </p>
          <p className="text-[11px] text-slate-400 mt-1">
            {monthExpenses.length} logged center expenditures
          </p>
        </div>

        {/* Net Surplus */}
        <div className="bg-white p-5 rounded-2xl border border-purple-100/80 shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">
              Net Monthly Operating Balance
            </span>
            <div className="p-1.5 rounded-lg bg-purple-50 text-[#6D0281]">
              <IndianRupee className="w-4 h-4" />
            </div>
          </div>
          <p className={`text-2xl font-extrabold mt-2 ${netSurplus >= 0 ? 'text-[#6D0281]' : 'text-red-700'}`}>
            ₹ {netSurplus.toLocaleString('en-IN')}
          </p>
          <p className="text-[11px] text-slate-400 mt-1">
            Surplus for clinical operations & equipment
          </p>
        </div>
      </div>

      {/* Itemized Inflow & Outflow Side-by-Side */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* Income Table */}
        <div className="bg-white rounded-2xl border border-purple-100/80 shadow-xs overflow-hidden">
          <div className="p-3.5 bg-emerald-50/70 border-b border-emerald-100 flex items-center justify-between">
            <h3 className="text-xs font-bold text-emerald-900 uppercase tracking-wider">
              Income Items ({monthInvoices.length})
            </h3>
            <span className="text-xs font-bold text-emerald-800">
              ₹ {totalIncome.toLocaleString('en-IN')}
            </span>
          </div>

          <div className="divide-y divide-slate-100 text-xs max-h-80 overflow-y-auto">
            {monthInvoices.length === 0 ? (
              <p className="p-4 text-slate-400 text-center text-xs">No invoices for this month.</p>
            ) : (
              monthInvoices.map((inv) => (
                <div key={inv.id} className="p-3 flex items-center justify-between gap-3">
                  <div>
                    <p className="font-bold text-slate-900">{inv.description}</p>
                    <p className="text-[10px] text-slate-400">
                      {inv.invoiceNumber} • {new Date(inv.issuedAt).toLocaleDateString('en-IN')}
                    </p>
                  </div>
                  <span className="font-extrabold text-emerald-700 shrink-0">
                    + ₹ {inv.amount.toLocaleString('en-IN')}
                  </span>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Expenses Table */}
        <div className="bg-white rounded-2xl border border-purple-100/80 shadow-xs overflow-hidden">
          <div className="p-3.5 bg-rose-50/70 border-b border-rose-100 flex items-center justify-between">
            <h3 className="text-xs font-bold text-rose-900 uppercase tracking-wider">
              Expense Items ({monthExpenses.length})
            </h3>
            <span className="text-xs font-bold text-rose-800">
              ₹ {totalExpense.toLocaleString('en-IN')}
            </span>
          </div>

          <div className="divide-y divide-slate-100 text-xs max-h-80 overflow-y-auto">
            {monthExpenses.length === 0 ? (
              <p className="p-4 text-slate-400 text-center text-xs">No expenses logged for this month.</p>
            ) : (
              monthExpenses.map((exp) => (
                <div key={exp.id} className="p-3 flex items-center justify-between gap-3">
                  <div>
                    <p className="font-bold text-slate-900">{exp.payee}</p>
                    <p className="text-[10px] text-slate-400">
                      {exp.category} • {exp.date}
                    </p>
                  </div>
                  <span className="font-extrabold text-rose-700 shrink-0">
                    - ₹ {exp.amount.toLocaleString('en-IN')}
                  </span>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
